title: Pfiu
description: Blog despre sănătate și lifestyle

url: https://pfiu.ro
baseurl: ""
paginate_path: "blog/page:num/"
permalink: :year/:month/:day/:title/

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Acasă
    url: /index.html
  - title: Despre
    url: /about
  - title: Contact
    url: /contact

social:
  github: alexandru
  twitter: alexelcu
  facebook: alexelcu
  email: contact@m9.pfiu.ro

# google_analytics: "UA-58263416-1"
