title: Alexandru Nedelcu (RO)
description: Explorări, dietă, viață

url: https://ro.alexn.org
baseurl: ""
permalink: :year/:month/:title/
feed: https://flux.ro.alexn.org/

include: ["_redirects"]

defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      has_comments: true

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ':title - pagina :num'
  sort_reverse: true

autopages:
  enabled: true

  categories:
    layouts:
      - 'auto-categorie.html'
  tags:
    layouts:
      - 'auto-tag.html'
  collections:
    enabled: false

navigation:
  - title: Acasă
    url: /index.html
  - title: Despre
    url: /despre/
  - title: Abonează-te
    url: /abonament/

authors:
  alexelcu:
    name: Alexandru Nedelcu
    github: alexandru
    twitter: alexelcu
    facebook: alexelcu

social:
  # github: alexandru
  # twitter: alexelcu
  # facebook: alexelcu
  email: contact@m9.alexn.org

google_analytics: "UA-84530423-4"

assets:
  destination: "/assets/compiled"
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  sources:
    - assets/media
