title: Pfiu.ro
description: Explorări, dietă, viață

url: https://pfiu.netlify.com
baseurl: ""
permalink: :year/:month/:day/:title/

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - pagina :num'
  sort_reverse: true

navigation:
  - title: Acasă
    url: /index.html
  - title: Despre
    url: /despre/
  - title: Contact
    url: /contact/
  - title: Abonează-te
    url: /abonament/

social:
  # github: alexandru
  # twitter: alexelcu
  # facebook: alexelcu
  email: contact@m9.pfiu.ro

google_analytics: "UA-84530423-4"
